from Config.config import images


def create_credit_massive_order_inv(sge_funct, archivo_productos):
    # esta funcion recibe como parametro una instancia de la clase SGE functions y un archivo co los productos
    print("5 Ingresar numero de sucursal ")
    sge_funct.send_text('12')
    sge_funct.segundos_de_espera(1)
    sge_funct.validar_sucursal_12_seleccionada()
    print("6 Press Enter")
    sge_funct.press_enter()
    print("7 Ingresar opcion de 'pedidos facturacion' ")
    sge_funct.send_text('4')
    print("8 Press Enter")
    sge_funct.press_enter()
    print("9 Ingresar opcion de 'ventas directas' ")
    sge_funct.send_text('10')
    print("10 Press Enter")
    sge_funct.press_enter()
    print("11 Ingresar cuenta ")
    sge_funct.send_text('45820263')
    print("12 presionar 3 veces enter para posicionarse en Domicilio de entrega")
    sge_funct.press_enter()
    print("13 Press Enter")
    sge_funct.press_enter()
    print("14 Press Enter")
    sge_funct.press_enter()
    print("15 Presionar enter por cuarta vez para seleccionar primer domicilio")
    sge_funct.press_enter()
    print("16 Presionar ctrl+w para continuar y abrir detalle del pedido")
    sge_funct.press_hotkeys('ctrl+w')
    print("17 tiempo_fuera_2")
    sge_funct.segundos_de_espera(2)
    print("18 Verificacion de promociones")
    while sge_funct.promociones_y_atrasos():
        sge_funct.press_hotkeys('ctrl+a')
    print("19 Presionar ctrl+o para ver la lista de opciones")
    sge_funct.press_hotkeys('ctrl+o')
    print("20 Presionar letra 'M' hasta encontrar la opcion ctrl+u Importar pedido masivo")
    sge_funct.send_text('m')
    print("21 Press Enter")
    sge_funct.press_enter()
    print("22 Leer archivo y escribir los datos de archivo tmpmasivo.txt (esto sustituye el clic derecho)")
    sge_funct.leer_archivo_productos(archivo_productos)
    print("23 Presionar 'Enter' para que muestre la ultima linea bien")
    sge_funct.press_enter()
    print("24 Presionamos 'ctrl + W' para continuar y pasar al detalle de facturacion")
    sge_funct.press_hotkeys('ctrl+w')
    print("25 Presionar ctrl+w para grabar lo capturado en la ventana")
    sge_funct.press_hotkeys('ctrl+w')
    print("26 Presionar ctrl+w para facturar")
    sge_funct.press_hotkeys('ctrl+w')
    print("27 Tiempo_fuera_5")
    sge_funct.segundos_de_espera(7)
    print("28 Presionar 'Enter' para continuar")
    sge_funct.press_enter()

