import time

from Config.config import images


def create_mostrador_simple_inv(sge_funct):

    print("5 Ingresar numero de sucursal ")
    sge_funct.send_text('12')
    sge_funct.segundos_de_espera(1)
    sge_funct.validar_sucursal_12_seleccionada()
    print("6 Press Enter")
    sge_funct.press_enter()
    print("7 Ingresar opcion de 'pedidos facturacion' ")
    sge_funct.send_text('4')
    print("8 Press Enter")
    sge_funct.press_enter()
    print("9 Ingresar opcion de 'ventas directas' ")
    sge_funct.send_text('10')
    print("10 Press Enter")
    sge_funct.press_enter()
    print("11 ingresar cuenta ")
    sge_funct.send_text('45828833')
    print("12 Verificacion de promociones ")
    while sge_funct.promociones_y_atrasos():
        sge_funct.press_hotkeys('ctrl+a')
    sge_funct.send_text('promociones')
    print("13 Presionar 'crtl + e' para abrir busqueda de linea ")
    sge_funct.press_hotkeys('ctrl+e')
    print("14 Ingresar numero de linea ")
    sge_funct.send_text('31')
    print("15 Press Enter")
    sge_funct.press_enter()
    print("16 Ingresar codigo ")
    sge_funct.send_text('1408')
    print("17 Press Enter")
    sge_funct.press_enter()
    print("18 Presionar 3 veces enter para posicionarse en columna 'cantidad' ")
    sge_funct.press_enter()
    print("19 Press Enter")
    sge_funct.press_enter()
    print("20 Press Enter")
    sge_funct.press_enter()
    print("21 Capturar 'cantidad'")
    sge_funct.send_text('2')
    print("22 Press Enter")
    sge_funct.press_enter()
    print("23 Press Enter")
    sge_funct.press_enter()
    print("24 Presionar ctrl+w para facturar lo capturado en ventana del detalle ")
    sge_funct.press_hotkeys('ctrl+w')
    print("25 Press Enter")
    sge_funct.press_enter()
    print("26 Presionar 'Tab' dos veces ")
    sge_funct.press_tab()
    print("27 Press Tab ")
    sge_funct.press_tab()
    print("28 Ingresar cuenta mostrador nota: el primer carácter es espacio")
    sge_funct.send_text(' 0274890')
    print("29 Presionar 'Enter' para seleccionar cliente buscado ")
    sge_funct.press_enter()
    print("30 Ingresar clave de agente y presionar 'Enter' ")
    sge_funct.send_text('06')
    print("31 Press Enter")
    sge_funct.press_enter()
    print("31 Presionar 'Enter' en campo 'referencia' sin capturar nada ")
    sge_funct.press_enter()
    print("32 Presionar 'Enter' en campo 'regimen fiscal' sin capturar nada ")
    sge_funct.press_enter()
    print("33 Presionar 'Enter' en campo 'Uso del CFDI' sin capturar nada ")
    sge_funct.press_enter()
    print("34 Presionar 'Enter' en campo 'Medio de entrega/enbarque' sin capturar nada ")
    sge_funct.press_enter()
    print("35 Presionar 'crtl + w' para regresar a la ventana del detalle ")
    sge_funct.press_hotkeys('ctrl+w')
    print("36 Presionar 'crtl + w' para facturar ")
    sge_funct.press_hotkeys('ctrl+w')
    print("37 Presionar 'crtl + w' para continuar ")
    sge_funct.press_hotkeys('ctrl+w')
    print("38 Posicionados en la columna Forma de Pago presionamos ctrl + R aplicar adeudo")
    sge_funct.press_hotkeys('ctrl+r')
    print("39 Presionar 'crtl + w' para grabar(generar factura) ")
    sge_funct.press_hotkeys('ctrl+w')
    print("40 Presionar 'Enter' para confirmar si es correcto ")
    sge_funct.press_enter()
    print("41 Tiempo_fuera_8")
    sge_funct.segundos_de_espera(8)
    print("42 Presionar 'Enter' para continuar ")
    sge_funct.press_enter()
