from Config.config import images


def MTC_INVSGE_015_steps(sge_funct):
    print("PASO")
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.segundos_de_espera(1)
    sge_funct.validar_sucursal_12_seleccionada()

    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('4')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Teclear input")
    sge_funct.send_text('10')
    print("7 Teclear input")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta 01018501")
    sge_funct.send_text('01018501')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 Teclear input")
    sge_funct.press_enter()
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Buscar el medio de entrega/embarque")
    sge_funct.press_hotkeys('ctrl+e')
    print("13 Capturar la paquetería DHL")
    sge_funct.send_text('DHL')
    print("14 Teclear input")
    sge_funct.press_enter()
    print("15 Teclear input")
    sge_funct.press_enter()
    print("16 Presionar ctrl + W para pasar al detalle del pedido")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(5)
    print("17 Posicionarse en Columna Linea y presionar la combinacion de teclas ctrl + E")
    sge_funct.press_hotkeys('ctrl+e')
    print("18 Ingresar la línea del producto")
    sge_funct.send_text('4x')
    print("19 Teclear input")
    sge_funct.press_enter()
    print("20 Escribimos el codigo")
    sge_funct.send_text('AMP-24-675')
    print("21 Teclear input")
    sge_funct.press_enter()
    print("22 Desde la línea del articulo obligado teclear flecha arriba")
    sge_funct.flecha_arriba()#coment
    print("23 Teclear input")
    sge_funct.press_enter()
    print("24 Teclear input")
    sge_funct.press_enter()
    print("25 Presionamos Enter hasta posicionarnos en la columna cantidad")
    sge_funct.press_enter()
    print("26 Capturamos N unidades")
    sge_funct.send_text('2')
    print("27 Teclear input")
    sge_funct.press_enter()
    print("28 Teclear input")
    sge_funct.press_enter()
    print("29 Presionamos ctrl + W para facturar lo capturado en la ventada del detalle esperar 5 segundos")
    sge_funct.press_hotkeys('ctrl+w')
    print("30 Presionamos ctrl + W para Continuar")
    sge_funct.press_hotkeys('ctrl+w')
    print("31 Posicionados en la columna Forma de Pago presionamos 3 veces la flecha abajo para posicionarse en tarjeta de credito")
    sge_funct.flecha_abajo()
    sge_funct.flecha_abajo()
    sge_funct.flecha_abajo()
    print("32 Capturar el total a liquidar")
    sge_funct.send_text('5,506.01')
    print("33 Seleccionar el banco de la primera opcion con enter")
    sge_funct.press_enter()
    print("34 Teclear input")
    sge_funct.press_enter()
    print("35 Capturar los ultimos cuatro digitos de la tarjeta 3452")
    sge_funct.send_text('3452')
    print("36 Presionamos ctrl + W para grabar (generar factura)")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(5)
    print("37 Presionamos Enter para continuar ")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(3)
    print("38 Presionamos Enter para continuar ")
    sge_funct.press_enter()