def MTC_INVSGE_020_steps(sge_funct):
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('4')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Teclear input")
    sge_funct.send_text('10')
    print("7 Teclear input")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta 01018501")
    sge_funct.send_text('01018501')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 Teclear input")
    sge_funct.press_enter()
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Buscar el medio de entrega/embarque")
    sge_funct.press_hotkeys('ctrl+e')
    print("13 Capturar la paquetería DHL")
    sge_funct.send_text('DHL')
    print("14 Teclear input")
    sge_funct.press_enter()
    print("15 Teclear input")
    sge_funct.press_enter()
    print("16 Presionar ctrl + W para pasar al detalle del pedido")
    sge_funct.press_hotkeys('ctrl+w')
    print("17 Posicionarse en Columna Linea y presionar la combinacion de teclas ctrl + o")
    sge_funct.press_hotkeys('ctrl+o')
    print("18 Presionamos ctrl + i")# workaround presionar k para seleccionar kits
    # sge_funct.send_text('ctrl+i')
    sge_funct.send_text('k')
    sge_funct.segundos_de_espera(2)
    print("19 Capturar el código del kit AM 206 CC,XS T 1.6 04-7")
    sge_funct.send_text('AM 206 CC')
    print("20 Teclear input")
    sge_funct.press_enter()
    print("21 Teclear input")
    sge_funct.press_enter()
    print("22 Teclear input")
    sge_funct.press_enter()
    print("23 Presionamos ctrl + W")
    sge_funct.press_hotkeys('ctrl+w')
    print("24 Presionamos ctrl + W para facturar lo capturado en la ventada del detalle esperar 5 segundos")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(5)
    print("25 Presionamos ctrl + W para Continuar")
    sge_funct.press_hotkeys('ctrl+w')
    print(
        "26 Posicionados en la columna Forma de Pago presionamos 3 veces la flecha abajo para posicionarse en tarjeta de credito")
    sge_funct.flecha_abajo()
    sge_funct.flecha_abajo()
    sge_funct.flecha_abajo()
    print("27 Capturar el total a liquidar")
    sge_funct.send_text('7,769.02')
    print("28 Seleccionar el banco de la primera opcion con enter")
    sge_funct.press_enter()
    print("29 Teclear input")
    sge_funct.press_enter()
    print("30 Capturar los ultimos cuatro digitos de la tarjeta 3452")
    sge_funct.send_text('3452')
    print("31 Presionamos ctrl + W para grabar (generar factura)")
    sge_funct.press_hotkeys('ctrl+w')
    print("32 Presiona Enter para confirmar que si esta correcto ")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    print("33 Presionamos Enter para continuar ")
    sge_funct.press_enter()






