from Config.config import images


def MTC_INVSGE_008_steps(sge_funct):
    print("***MTC_ASGE_008-Facturacion_sencilla_mostrador_plaza_equivalente***")
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.segundos_de_espera(1)
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input Enter")
    sge_funct.press_enter()
    print("4 Teclear input 4")
    sge_funct.send_text('4')
    print("5 Teclear input Enter")
    sge_funct.press_enter()
    print("6 Teclear input 10")
    sge_funct.send_text('10')
    print("7 Teclear input Enter")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta 45828833")
    sge_funct.send_text('45828833')
    print("9 Posicionarse en Columna Linea y presionar la combinacion de teclas")
    sge_funct.press_hotkeys('ctrl+e')
    print("10 capturamos la linea")
    sge_funct.send_text('31')
    print("11 Teclear input Enter")
    sge_funct.press_enter()
    print("12 Escribimos el codigo")
    sge_funct.send_text('1408')
    print("13 Teclear input Enter")
    sge_funct.press_enter()
    print("14 Presionamos ctrl+l para ver los articulos equivalentes")
    sge_funct.press_hotkeys('ctrl+l')
    print("15 Posicionarnos en el articulo 01  30    173596 e ingresamos 1")
    sge_funct.send_text('1')
    print("16 Teclear input Enter")
    sge_funct.press_enter()
    print("17 Presionamos ctrl+w para grabar")
    sge_funct.press_hotkeys('ctrl+w')
    print("18 Teclear input Enter")
    sge_funct.press_enter()
    #AGREGUE ESTE ENTER ADICIONAL  PONERLO EN LOS PASOS
    print("18 Teclear input Enter")
    sge_funct.press_enter()
    print("19 Presionamos ctrl + W para facturar lo capturado en la ventana del detalle")
    sge_funct.press_hotkeys('ctrl+w')
    print("20 Presionarmos Enter Para seleccionar al cliente de mostrador")
    sge_funct.press_enter()
    print("21 Teclear input tab")
    sge_funct.press_tab()
    print("22 Teclear input tab")
    sge_funct.press_tab()
    print("23 y capturamos la cuenta  0274890 (el primer carácter es espacios)")
    sge_funct.send_text(' 0274890')
    print("24 Teclear input Enter")
    sge_funct.press_enter()
    print("25 Capturamos clave del agente 06")
    sge_funct.send_text('06')
    print("26 Teclear input Enter")
    sge_funct.press_enter()
    print("27 Presionamos Enter sin capturar nada sobre el campo referencia")
    sge_funct.press_enter()
    print("28 Presionamos Enter sin capturar nada sobre el campo Regimen Fiscal")
    sge_funct.press_enter()
    print("29 Presionamos Enter sin capturar nada sobre el campo Uso del CFDI")
    sge_funct.press_enter()
    print("30 Presionamos Enter sin capturar nada sobre el campo Medio de entrega/embarque")
    sge_funct.press_enter()
    print("31 Presionamos ctrl + W para regresar a la ventana del Detalle")
    sge_funct.press_hotkeys('ctrl+w')
    print("32 Presionamos ctrl + W para Facturar")
    sge_funct.press_hotkeys('ctrl+w')
    print("33 Presionamos ctrl + W para Continuar")
    sge_funct.press_hotkeys('ctrl+w')
    print("34 Posicionados en la columna Forma de Pago presionamos ctrl + R aplicar adeudo")
    sge_funct.press_hotkeys('ctrl+r')
    print("35 Presionamos ctrl + W para grabar (generar factura)")
    sge_funct.press_hotkeys('ctrl+w')
    print("36 Presiona Enter para confirmar que si esta correcto ")
    sge_funct.press_enter()
    print("37 Presionamos Enter para continuar ")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    print("38 Presionamos Enter para continuar ")
    sge_funct.press_enter()
