from Config.config import images


def MTC_INVSGE_006_steps(sge_funct):
    print("***MTC_ASGE_006-Facturacion_sencilla_credito_plaza_equivalente***")
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.segundos_de_espera(1)
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input Enter")
    sge_funct.press_enter()
    print("4 Teclear input 4")
    sge_funct.send_text('4')
    print("5 Teclear input Enter")
    sge_funct.press_enter()
    print("6 Teclear input 10")
    sge_funct.send_text('10')
    print("7 Teclear input Enter")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta 45820263")
    sge_funct.send_text('45820263')
    print("9 Teclear input Enter")
    sge_funct.press_enter()
    print("10 Teclear input Enter")
    sge_funct.press_enter()
    print("11 Teclear input Enter")
    sge_funct.press_enter()
    print("12 Presionar enter por cuarta vez para seleccionar primer domicilio")
    sge_funct.press_enter()
    print("13 Presionar ctrl + W para pasar al detalle del pedido")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(2)
    print("14 Aparece mensaje de promociones o advertencias de la cuenta")
    while sge_funct.promociones_y_atrasos():
        sge_funct.press_hotkeys('ctrl+a')
    print("15 Posicionarse en Columna Linea y presionar la combinacion de teclas ctrl + E")
    sge_funct.press_hotkeys('ctrl+e')
    print("16 Ingresar la línea del producto")
    sge_funct.send_text('31')
    print("17 Teclear input Enter")
    sge_funct.press_enter()
    print("18 Escribimos el codigo 1408")
    sge_funct.send_text('1408')
    print("19 Teclear input Enter")
    sge_funct.press_enter()
    print("20 Presionamos ctrl+l para ver los articulos equivalentes")
    sge_funct.press_hotkeys('ctrl+l')
    print("21 Posicionarnos en el articulo 01  30    173596 e ingresamos 1")
    sge_funct.send_text('1')
    print("22 Teclear input Enter")
    sge_funct.press_enter()
    print("23 Presionamos ctrl+w para grabar")
    sge_funct.press_hotkeys('ctrl+w')
    print("24 Teclear input Enter")
    sge_funct.press_enter()
    print("25 Presionamos ctrl + W para facturar lo capturado en la ventada del detalle esperar 5 segundos")
    sge_funct.press_hotkeys('ctrl+w')
    print("26 Presionamos Enter para continuar ")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    # print("27 Presionamos Enter para continuar ")
    # sge_funct.press_enter()
