from Config.config import images


def MTC_INVSGE_007_steps(sge_funct):
    print("***MTC_ASGE_007-Facturacion_sencilla_credito_foraneo_equivalente***")
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.segundos_de_espera(1)
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input Enter")
    sge_funct.press_enter()
    print("4 Teclear input 4")
    sge_funct.send_text('4')
    print("5 Teclear input Enter")
    sge_funct.press_enter()
    print("6 Teclear input 10")
    sge_funct.send_text('10')
    print("7 Teclear input Enter")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta 03016701")
    sge_funct.send_text('03016701')
    print("9 Capturar la letra s")
    sge_funct.send_text('s')
    print("10 Teclear input Enter")
    sge_funct.press_enter()
    print("11 posicionarno en el medio de embarque Enter")
    sge_funct.press_enter()
    print("12 Presionar ctrl+e")
    sge_funct.press_hotkeys('ctrl+e')
    print("13 Teclear input tab")
    sge_funct.press_tab()
    print("14 Capturar 02")
    sge_funct.send_text('2')
    print("15 Teclear input Enter")
    sge_funct.press_enter()
    print("16 Teclear input Enter")
    sge_funct.press_enter()
    print("17 Presionamos ctrl+w")
    sge_funct.press_hotkeys('ctrl+w')
    print("18 Presionamos ctrl+a")
    sge_funct.press_hotkeys('ctrl+a')
    print("19 Ingresar la línea del producto")
    sge_funct.send_text('31')
    print("20 Teclear input Enter")
    sge_funct.press_enter()
    print("21 Escribimos el codigo 1408")
    sge_funct.send_text('1408')
    print("22 Teclear input Enter")
    sge_funct.press_enter()
    print("21 Escribimos el almacen 01")
    sge_funct.send_text('01')
    print("22 Teclear input Enter")
    sge_funct.press_enter()
    print("23 Presionamos ctrl+l para ver los articulos equivalentes")
    sge_funct.press_hotkeys('ctrl+l')
    print("24 Posicionarnos en el articulo 01  30    173596 e ingresamos 1")
    sge_funct.send_text('1')
    print("25 Teclear input Enter")
    sge_funct.press_enter()
    print("26 Presionamos ctrl+w para grabar")
    sge_funct.press_hotkeys('ctrl+w')
    print("27 Teclear input Enter")
    sge_funct.press_enter()
    print("28 Presionamos ctrl + W para facturar lo capturado en la ventana del detalle")
    sge_funct.press_hotkeys('ctrl+w')
    print("29 Capturar la letra s")
    sge_funct.send_text('s')
    print("30 Presionamos Enter para continuar ")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    print("31 Presionamos Enter para continuar ")
    sge_funct.press_enter()
