def MTC_INVSGE_016_steps(sge_funct):
    print("1 Ingresar a SGE con las credenciales <<User>> <Password>>")
    sge_funct.send_text('')
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('4')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Teclear input")
    sge_funct.send_text('10')
    print("7 Teclear input")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta 45820263")
    sge_funct.send_text('45820263')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 Teclear input")
    sge_funct.press_enter()
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Teclear input")
    sge_funct.press_enter()
    print("13 Presionar ctrl + W para pasar al detalle del pedido")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(2)
    print("14 Aparece mensaje de promociones o advertencias de la cuenta")
    while sge_funct.promociones_y_atrasos():
        sge_funct.press_hotkeys('ctrl+a')
    print("15 Posicionarse en Columna Linea y presionar la combinacion de teclas ctrl + o")
    sge_funct.press_hotkeys('ctrl+o')
    sge_funct.segundos_de_espera(2)
    print("16 Presionamos ctrl + i") # workaround presionar k para seleccionar kits
    # sge_funct.send_text('ctrl+i')
    sge_funct.send_text('k')
    sge_funct.segundos_de_espera(2)
    print("17 Capturar el código del kit")
    sge_funct.send_text('AM 206 CC,XS T 1.6 ')# 'AM 206 CC,XS T 1.6 04-7' se quito el 04-7 porque excede caracteres de captura
    print("18 Teclear input")
    sge_funct.press_enter()
    print("19 Teclear input")
    sge_funct.press_enter()
    print("20 Teclear input")
    sge_funct.press_enter()
    print("21 Presionamos ctrl + W")
    sge_funct.press_hotkeys('ctrl+w')
    print("22 Presionamos ctrl + W para facturar lo capturado en la ventada del detalle esperar 5 segundos")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(5)
    print("23 Presionamos Enter para continuar ")
    sge_funct.press_enter()


