from Config.config import images


def MTC_INVSGE_012_steps(sge_funct):
    print("PASO")
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.segundos_de_espera(1)
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('4')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Teclear input")
    sge_funct.send_text('10')
    print("7 Teclear input")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta 03016701")
    sge_funct.send_text('03016701')
    print("9 Capturar la letra s")
    sge_funct.send_text('s')
    print("10 Teclear input")
    sge_funct.press_enter()
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Presionamos ctrl+e")
    sge_funct.press_hotkeys('ctrl+e')
    print("13 Teclear input")
    sge_funct.press_tab()
    print("14 Capturar 02")
    sge_funct.send_text('02')
    print("15 Teclear input")
    sge_funct.press_enter()
    print("16 Teclear input")
    sge_funct.press_enter()
    print("17 Presionamos ctrl +w")
    sge_funct.press_hotkeys('ctrl+w')
    print("18 Se visualizan promociones o advertencias")
    while sge_funct.promociones_y_atrasos():
        sge_funct.press_hotkeys('ctrl+a')
    print("19 Posicionarse en Columna Linea y presionar la combinacion de teclas")
    sge_funct.press_hotkeys('ctrl+e')
    print("20 Ingresar la línea del producto")
    sge_funct.send_text('4x')
    print("21 Teclear input")
    sge_funct.press_enter()
    print("22 Escribimos el codigo")
    sge_funct.send_text('AMP-24-675')
    print("23 Teclear input")
    sge_funct.press_enter()
    print("24 Desde la línea del articulo obligado teclear flecha arriba")
    sge_funct.flecha_arriba()#coment
    print("25 Teclear input")
    sge_funct.press_enter()
    print("26 Teclear input")
    sge_funct.press_enter()
    print("27 Presionamos Enter hasta posicionarnos en la columna cantidad")
    sge_funct.press_enter()
    print("28 Capturamos N unidades")
    sge_funct.send_text('2')
    print("29 Teclear input")
    sge_funct.press_enter()
    print("30 Presionamos ctrl + W para facturar lo capturado en la ventada del detalle esperar 5 segundos")
    sge_funct.press_hotkeys('ctrl+w')
    print("31 Capturar la letra s ")
    sge_funct.send_text('s')
    sge_funct.segundos_de_espera(5)
    print("32 Presionamos Enter para continuar ")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(3)