from Config.config import images


def MTC_INVSGE_023_steps(sge_funct, archivo_productos):
    # esta funcion recibe como parametro una instancia de la clase SGE functions y un archivo co los productos
    print("2 Ingresar numero de sucursal ")
    sge_funct.send_text('12')
    sge_funct.segundos_de_espera(1)
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Press Enter")
    sge_funct.press_enter()
    print("4 Ingresar opcion de 'pedidos facturacion' ")
    sge_funct.send_text('4')
    print("5 Press Enter")
    sge_funct.press_enter()
    print("6 Ingresar opcion de 'ventas directas' ")
    sge_funct.send_text('10')
    print("7 Press Enter")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta")
    sge_funct.send_text('45820263')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 Teclear input")
    sge_funct.press_enter()
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Teclear input")
    sge_funct.press_enter()
    print("13 Presionar ctrl + W para pasar al detalle del pedido")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(2)
    print("14 Aparece mensaje de promociones o advertencias de la cuenta")
    while sge_funct.promociones_y_atrasos():
        sge_funct.press_hotkeys('ctrl+a')
    print("15 Presionamos ctrl + O para más opciones")
    sge_funct.press_hotkeys('ctrl+o')
    print("16 Presionar Letra M Importa pedido masivo")
    sge_funct.send_text('m')
    print("17 Presionamos Enter para continuar ")
    sge_funct.press_enter()
    print("18 Oprimir click derecho del mouse para Pegar los datos de los articulos a facturar tmpmasivo.txt")
    sge_funct.leer_archivo_productos(archivo_productos)
    print("19 Presionamos ctrl + W")
    sge_funct.press_hotkeys('ctrl+w')
    print("20 Presionamos ctrl + W")
    sge_funct.press_hotkeys('ctrl+w')
    print("21 Presionamos ctrl + W")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(10)
    print("22 Presionamos ctrl + W para facturar lo capturado en la ventada del detalle")
    sge_funct.press_hotkeys('ctrl+w')
    sge_funct.segundos_de_espera(60)
    print("23 Presionamos Enter para continuar ")
    sge_funct.press_enter()
