def MTC_INVSGE_018_steps(sge_funct):
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('4')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Teclear input")
    sge_funct.send_text('10')
    print("7 Teclear input")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta 45828833")
    sge_funct.send_text('45828833')
    print("9 Posicionarse en Columna Linea y presionar la combinacion de teclas ctrl + o")
    sge_funct.press_hotkeys('ctrl+o')
    print("10 Presionamos ctrl + i")  # workaround presionar k para seleccionar kits
    #sge_funct.send_text('ctrl+i')
    sge_funct.send_text('k')
    sge_funct.segundos_de_espera(2)
    print("11 Capturar el código del kit AM 206 CC,XS T 1.6 04-7")
    sge_funct.send_text('AM 206 CC')
    print("12 Teclear input")
    sge_funct.press_enter()
    print("13 Teclear input")
    sge_funct.press_enter()
    print("14 Teclear input")
    sge_funct.press_enter()
    print("15 Presionamos ctrl + W")
    sge_funct.press_hotkeys('ctrl+w')
    print("16 Presionamos ctrl + W para facturar lo capturado en la ventana del detalle")
    sge_funct.press_hotkeys('ctrl+w')
    print("17 Presionarmos Enter Para seleccionar al cliente de mostrador")
    sge_funct.press_enter()
    print("18 Teclear input")
    sge_funct.press_tab()
    print("19 Teclear input")
    sge_funct.press_tab()
    print("20  y capturamos la cuenta  0274890 (el primer carácter es espacios)")
    sge_funct.send_text(' 0274890')
    print("21 Teclear input")
    sge_funct.press_enter()
    print("22 Capturamos clave del agente 06")
    sge_funct.send_text('06')
    print("23 Teclear input")
    sge_funct.press_enter()
    print("24 Presionamos Enter sin capturar nada sobre el campo referencia")
    sge_funct.press_enter()
    print("25 Presionamos Enter sin capturar nada sobre el campo Regimen Fiscal")
    sge_funct.press_enter()
    print("26 Presionamos Enter sin capturar nada sobre el campo Uso del CFDI")
    sge_funct.press_enter()
    print("27 Presionamos Enter sin capturar nada sobre el campo Medio de entrega/embarque")
    sge_funct.press_enter()
    print("28 Presionamos ctrl + W para regresar a la ventana del Detalle")
    sge_funct.press_hotkeys('ctrl+w')
    print("29 Presionamos ctrl + W para Facturar")
    sge_funct.press_hotkeys('ctrl+w')
    print("30 Presionamos ctrl + W para Continuar")
    sge_funct.press_hotkeys('ctrl+w')
    print("31 Posicionados en la columna Forma de Pago presionamos ctrl + R aplicar adeudo")
    sge_funct.press_hotkeys('ctrl+r')
    print("32 Presionamos ctrl + W para grabar (generar factura)")
    sge_funct.press_hotkeys('ctrl+w')
    print("33 Presiona Enter para confirmar que si esta correcto ")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
    print("34 Presionamos Enter para continuar ")
    sge_funct.press_enter()


