import time

from Config.config import images, login_data


def MTC_INVSGE_029_steps(sge_funct, img_inicioFactura):
    # -------------------------------------------------------------------------1
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('4')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Teclear input")
    sge_funct.send_text('10')
    print("7 Teclear input")
    sge_funct.press_enter()
    print("8 Posicionarse en campo cuenta y capturar la cuenta 45828833")
    sge_funct.send_text('45828833')
    print("9 Posicionarse en Columna Linea y presionar la combinacion de teclas")
    sge_funct.press_hotkeys('ctrl+e')
    print("10 capturamos la linea 31")
    sge_funct.send_text('31')
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Escribimos el codigo 1408 ")
    sge_funct.send_text('1408')
    print("13 Teclear input")
    sge_funct.press_enter()
    print("14 Presionamos Enter hasta posicionarnos en la columna cantidad ")
    sge_funct.press_enter()
    print("15 Teclear input")
    sge_funct.press_enter()
    print("16 Teclear input")
    sge_funct.press_enter()
    print("17 Capturamos N unidades")
    sge_funct.send_text('2')
    print("18 Teclear input")
    sge_funct.press_enter()
    print("19 Presionamos Enter sin editar la columna importe")
    sge_funct.press_enter()
    print("20 Presionamos ctrl + W para facturar lo capturado en la ventana del detalle")
    sge_funct.press_hotkeys('ctrl+w')
    print("21 Presionarmos Enter Para seleccionar al cliente de mostrador")
    sge_funct.press_enter()
    print("22 Teclear input")
    sge_funct.press_tab()
    print("23 Teclear input")
    sge_funct.press_tab()
    print("24  y capturamos la cuenta  0274890 (el primer carácter es espacios)")
    sge_funct.send_text(' 0274890')
    print("25 Teclear input")
    sge_funct.press_enter()
    print("26 Capturamos clave del agente 06")
    sge_funct.send_text('06')
    print("27 Teclear input")
    sge_funct.press_enter()
    print("28 Presionamos Enter sin capturar nada sobre el campo referencia")
    sge_funct.press_enter()
    print("29 Presionamos Enter sin capturar nada sobre el campo Regimen Fiscal")
    sge_funct.press_enter()
    print("30 Presionamos Enter sin capturar nada sobre el campo Uso del CFDI")
    sge_funct.press_enter()
    print("31 Presionamos Enter sin capturar nada sobre el campo Medio de entrega/embarque")
    sge_funct.press_enter()
    print("32 Presionamos ctrl + W para regresar a la ventana del Detalle")
    sge_funct.press_hotkeys('ctrl+w')
    print("33 Presionamos ctrl + W para Facturar")
    sge_funct.press_hotkeys('ctrl+w')
    print("34 Presionamos ctrl + W para Continuar")
    sge_funct.press_hotkeys('ctrl+w')
    print("35 Posicionados en la columna Forma de Pago presionamos ctrl + R aplicar adeudo")
    sge_funct.press_hotkeys('ctrl+r')
    print("36 Presionamos ctrl + W para grabar (generar factura)")
    sge_funct.press_hotkeys('ctrl+w')
    print("37 Presiona Enter para confirmar que si esta correcto ")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(8)
    print("38 Presionamos Enter para continuar ")
    sge_funct.press_enter()
    # print("39 Presionamos Enter para continuar ")
    # sge_funct.press_enter()

    num_factura = sge_funct.doubleclick_axis_x(img_inicioFactura, 10)
    print(f"Factura Generada: {num_factura}")
    assert num_factura is not None
    sge_funct.close_sge_session()
    # -------------------------------------------------------------------------1
    print("------------------------------------------------------------------------ inicia TC 29")
    print("Trying to Connect...")
    sge_funct.sge_connection(login_data.linux_username, login_data.ip, login_data.password)
    print("Validating connection...")
    assert sge_funct.validate_adm_sge_connection(
        images.img_sge_adm_pantalla_inicial), "Error Found, SGE Connection Failed!!"

    print("1 Ingresar a SGE con las credenciales <<User>> <Password>>")
    sge_funct.send_text('')
    print("2 Ingresar en el teclado el <<Numero de sucursal>>")
    sge_funct.send_text('12')
    sge_funct.validar_sucursal_12_seleccionada()
    print("3 Teclear input")
    sge_funct.press_enter()
    print("4 Teclear input")
    sge_funct.send_text('4')
    print("5 Teclear input")
    sge_funct.press_enter()
    print("6 Capturamos la opción 13")
    sge_funct.send_text('13')
    print("7 Teclear input")
    sge_funct.press_enter()
    print("8 Capturamos la opción 1 devoluciones")
    sge_funct.send_text('1')
    print("9 Teclear input")
    sge_funct.press_enter()
    print("10 En el campo factura pegar el numero de la factura con clic derecho")
    sge_funct.send_text(num_factura)
    print("11 Teclear input")
    sge_funct.press_enter()
    print("12 Posicionarnos en la opción Dev. Cambio Medida de Producto")
    for i in range(5):
        sge_funct.flecha_abajo()
    print("13 Teclear input")
    sge_funct.press_enter()
    print("14 Capturar bodega/almacen")
    sge_funct.send_text('01')
    print("15 Capturar ctrl+v para cargar la información")
    sge_funct.press_hotkeys('ctrl+v')
    print("16 Teclear enter para seleccionar el primer articulo")
    sge_funct.press_enter()
    print("17 Capturar la cantidad a devolver")
    sge_funct.send_text('1')
    print("18 Teclear input")
    sge_funct.press_enter()
    print("19 Capturar ctrl+w")
    sge_funct.press_hotkeys('ctrl+w')
    print("20 Teclear input")
    sge_funct.press_enter()
    print("21 Teclear input")
    sge_funct.press_enter()
    print("22 Teclear input")
    sge_funct.press_enter()
    print("23 Capturar ctrl+w")
    sge_funct.press_hotkeys('ctrl+w')
    print("24 Capturar si")
    sge_funct.send_text('s')
    print("25 Teclear input")
    sge_funct.press_enter()
    sge_funct.segundos_de_espera(5)
